# MySQL Credentials
mysql:
  ip: 'localhost'
  port: '3306'
  user: 'user'
  pass: 'pass'
  db: 'VotePlugin'
  max-connections: 2

# What do you want to come up in chat when users run the /vote command.
#
# Available placeholders:
# {voteparty_current} => current amount of votes for the voteparty
# {voteparty_required} => amount of votes required for voteparty
# {voteparty_missing} => amount of votes missing for voteparty
voteCommand:
  - '&aVote for rewards:'
  - '&eRewards:'
  - '&7- $10,000'
  - '&7- 1x Vote Crate Key'
  - ' '
  - '&eLinks:'
  - '&7#1- link1.com/vote'
  - '&7#2- link2.com/vote'
  - '&7#3- link3.com/vote'
  - ' '
  - '&eVoteParty in {voteparty_missing} votes!'

# Here you can use [msg] to send the player a message. For example '[msg] &aThanks for voting!'
# You can also use [broadcast] to broadcast a message to the entire server. For example '[broadcast] %player% has voted and received awesome rewards! Use /vote now!'
#
# Available placeholders:
# %player% => player name
# %player_uuid% => player uuid (only works when online-only is set to true)
voteRewards:
  online-only: true
  rewards:
  - '[broadcast]&7[&eVote&7] &6%player% &ehas voted and received awesome rewards! &7(/vote)'
  - '[msg]&aThanks for voting and helping the server grow! Here are your rewards!'
  - 'crate give %player% Vote 1'
  - 'eco give %player% 10000'

# VoteParty settings
voteParty:
  enabled: true
  votesRequired: 200
  announcement:
    - '&4&m-----------------------------------------------&f'
    - ' '
    - '                             &4&lAttention'
    - '         &cA Vote Party is starting in 30 seconds!'
    - '                Make space in your inventory!&c'
    - ' '
    - '&4&m-----------------------------------------------&f'
  # A delay in seconds before the commands start executing
  delay: 30
  global-commands:
    - 'crate giveall Rare 1'
  # Available placeholders:
  # %player% => player name
  # %player_uuid% => player uuid
  per-player-commands:
    - 'eco give %player% 10000'
  concluded:
    - '&4The vote party has concluded!'

# Vote Token System
voteTokens:
  enabled: true
  tokensPerVote: 1

# Whether or not to remind users they havent voted in the last 24h. The plugin checks every 5 minutes.
voteReminder:
  enabled: true
  message:
    - '&6&m-----------------------------------------------&f'
    - ' '
    - '                             &6&lReminder'
    - '         &eYou haven''t voted in the last 24 hours'
    - '     &7(Please vote (/vote) to get rid of this message)'
    - ' '
    - '&6&m-----------------------------------------------&f'

# Whether or not /voteshop is enabled. A shop that uses vote tokens as currency.
voteShop:
  enabled: true
  invSize: 27
  invName: '&e&lVote Shop'
  fill: true
  fillItem:
    item: STAINED_GLASS_PANE
    data: 15
    amount: 1
    name: ' '
  items:
    1:
      slot: 10
      cost: 10
      displayItem:
        item: TRIPWIRE_HOOK
        data: 0
        amount: 1
        name: '&eVote Crate'
        lore:
          - 'use at warp crates'
      commands:
        - 'crate give %player% Vote 1'
    2:
      slot: 11
      cost: 25
      displayItem:
        item: TRIPWIRE_HOOK
        data: 0
        amount: 1
        name: '&eCommon Crate'
        lore:
          - 'use at warp crates'
      commands:
        - 'crate give %player% Common 1'
    3:
      slot: 12
      cost: 50
      displayItem:
        item: TRIPWIRE_HOOK
        data: 0
        amount: 1
        name: '&eRare Crate'
        lore:
          - 'use at warp crates'
      commands:
        - 'crate give %player% Rare 1'