# MySQL Credentials
mysql:
  ip: 'localhost'
  port: '3306'
  user: 'user'
  pass: 'pass'
  db: 'VotePlugin'
  max-connections: 2

# What do you want to come up in chat when users run the /vote command.
#
# Available placeholders:
# {voteparty_current} => current amount of votes for the voteparty
# {voteparty_required} => amount of votes required for voteparty
# {voteparty_missing} => amount of votes missing for voteparty
voteCommand:
  - '&aVote for rewards:'
  - '&eRewards:'
  - '&7- $10,000'
  - '&7- 1x Vote Crate Key'
  - ' '
  - '&eLinks:'
  - '&7#1- link1.com/vote'
  - '&7#2- link2.com/vote'
  - '&7#3- link3.com/vote'
  - ' '
  - '&eVoteParty in {voteparty_missing} votes!'

# Here you can use [msg] to send the player a message. For example '[msg] &aThanks for voting!'
# You can also use [broadcast] to broadcast a message to the entire server. For example '[broadcast] %player% has voted and received awesome rewards! Use /vote now!'
#
# Available placeholders:
# %player% => player name
# %player_uuid% => player uuid (only works when online-only is set to true)
voteRewards:
  online-only: true
  rewards:
  - '[broadcast]&7[&eVote&7] &6%player% &ehas voted and received awesome rewards! &7(/vote)'
  - '[msg]&aThanks for voting and helping the server grow! Here are your rewards!'
  - 'crate give %player% Vote 1'
  - 'eco give %player% 10000'

# VoteParty settings
voteParty:
  enabled: true
  votesRequired: 200
  announcement:
    - '                 &4&lAttention'
    - '   &cA vote party is starting in 30 seconds. Please make space'
    - '   &cin your inventory!'
  # A delay in seconds before the commands start executing
  delay: 30
  global-commands:
    - 'crate giveall Rare 1'
  # Available placeholders:
  # %player% => player name
  # %player_uuid% => player uuid
  per-player-commands:
    - 'eco give %player% 10000'
  concluded:
    - '&4The vote party has concluded!'

# Vote Token System
voteTokens:
  enabled: true
  tokensPerVote: 1