name: VotePlugin
version: ${project.version}
main: com.dnyferguson.voteplugin.VotePlugin
depend: [MomentoUserCache]
api-version: 1.16
softdepend: [PlaceholderAPI]
commands:
  vote:
  voteparty:
    aliases: ['vp']
  fakevote:
  voteshop:
  vpmain:
    aliases: ['votepartymain', 'votemain']
  keyall:
  raffle:
  rafflereset:
  addraffleentry:
